name: math_app
description: "Project to help my dad."

version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  realm: ^3.1.0
  intl: ^0.19.0
  widget_marquee: ^0.0.8
  easy_mask: ^2.0.1
  json_annotation: ^4.8.1
  http: ^1.2.1
  share_plus: ^9.0.0
  shared_preferences: ^2.2.2
  firebase_core: ^3.3.0
  firebase_analytics: ^11.2.1
  firebase_crashlytics: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
